### ISSUE TITLE
请问该如何使用

### ISSUE THREAD

**Issue by fu931113** [577fkj/doc88#1]
运行程序，报错
Errno 2] No such file or directory: 'pages/1.swf'
Traceback (most recent call last):
  File "C:\Users\97675\PycharmProjects\pythonProject2\doc88-main\main.py", line 198, in get_page
    with open('pages/' + str(count) + '.swf', "wb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'pages/1.swf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\97675\PycharmProjects\pythonProject2\doc88-main\main.py", line 240, in <module>
    doc88.get_page(1)
  File "C:\Users\97675\PycharmProjects\pythonProject2\doc88-main\main.py", line 202, in get_page
    with open('pages/' + str(count) + '-ph.ebt', "wb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'pages/1-ph.ebt'

**Comment by 577fkj** [comment]
在目录下新建一个pages文件夹就可以用了 swf转pdf目前还未实现 要看只能使用flash
